[project]
name = "seqforge"
version = "0.1.0"
description = "A modern Python toolkit for biological sequence analysis."
readme = "README.md"
authors = [
    { name = "ThorinOakenShield97", email = "eguillen.galvez@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
seqforge = "seqforge:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"
